-- created with TexturePacker (http://www.texturepacker.com)

roomLevels_pin_map = {
	
	["0.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=736,y=242,
		width=28,height=46
	},
	["1.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=308,y=880,
		width=19,height=46
	},
	["2.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=728,y=394,
		width=27,height=46
	},
	["3.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=736,y=338,
		width=27,height=46
	},
	["4.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=736,y=2,
		width=30,height=46
	},
	["5.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=736,y=290,
		width=27,height=46
	},
	["6.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=736,y=194,
		width=28,height=46
	},
	["7.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=736,y=146,
		width=28,height=46
	},
	["8.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=736,y=98,
		width=28,height=46
	},
	["9.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=736,y=50,
		width=28,height=46
	},
	["arrow_down.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=728,y=442,
		width=32,height=29
	},
	["arrow_up.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=203,y=934,
		width=32,height=29
	},
	["baseChip.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=106,y=880,
		width=100,height=52
	},
	["cheat_icon.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=259,y=880,
		width=47,height=83
	},
	["dou.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=750,y=815,
		width=13,height=46
	},
	["faststart_btn.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=333,y=815,
		width=415,height=165
	},
	["gameName_bg.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=369,y=693,
		width=397,height=120
	},
	["icon_market.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=2,y=880,
		width=102,height=98
	},
	["levelIcon_12.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=369,y=2,
		width=365,height=390
	},
	["levelIcon_13.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=2,y=394,
		width=365,height=390
	},
	["levelIcon_14.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=2,y=2,
		width=365,height=390
	},
	["newGamesIcon.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=106,y=934,
		width=95,height=23
	},
	["pulldown_bg.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=369,y=394,
		width=357,height=297
	},
	["pulldown_itembg.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=2,y=786,
		width=329,height=92
	},
	["wan.png"]={ 
		file="zhajinhua/res/login/roomLevels_pin.png",
		x=208,y=880,
		width=49,height=52
	},
}


return roomLevels_pin_map